application: holy-avenger
version: master
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /(.+)
  static_files: \1
  upload: .*
  
- url: /
  static_files: index.html
  upload: index.html
 